version: "3.5"

services:
  rp:
    image: vxnexus-registry.intra.inist.fr:8083/bibcnrs/shibboleth-sp3:2.0
    ports:
        - "8443:443"
    environment:
        - http_proxy
        - https_proxy
        - APPLI_APACHE_SERVERNAME
        - APPLI_APACHE_SERVERADMIN
        - APPLI_APACHE_LOGLEVEL
        - DOCKER_HOST_IP
    working_dir: /var/www/html
    volumes:
        - ./shibboleth/log:/var/log/shibboleth/
        - ./shibboleth/:/etc/shibboleth/
        - ./shibboleth/ssl:/etc/shibboleth/ssl
        - ./apache2/sites-available:/etc/apache2/sites-available
    restart: always
    networks:
      - bib-frontend-network

networks:
  bib-frontend-network:
    external: true
